/*****************************************************************************
  AUTO-GENERATED CODE:  Graphics Resource Converter version: 4.01.00

  Company:
      Microchip Technology, Inc.
 
  File Name:
     image_resources_epd_2.0_inch_demo.h
 
  Summary:
      This file is generated by the Microchip's Graphics Resource Converter.
  Description:
      This file is generated by the Graphics Resource Converter containing
      resources such as images and fonts that can be used by Microchip's
      Graphics Library, which is part of the MLA.
 *****************************************************************************/

// DOM-IGNORE-BEGIN
/*****************************************************************************
  Software License Agreement

  Copyright(c) 2013 Microchip Technology Inc.  All rights reserved.
  Microchip licenses to you the right to use, modify, copy and distribute
  Software only when embedded on a Microchip microcontroller or digital
  signal controller that is integrated into your product or third party
  product (pursuant to the sublicense terms in the accompanying license
  agreement).
 
  You should refer to the license agreement accompanying this Software
  for additional information regarding your rights and obligations.
 
  SOFTWARE AND DOCUMENTATION ARE PROVIDED “AS IS” WITHOUT WARRANTY OF ANY
  KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION, ANY WARRANTY
  OF MERCHANTABILITY, TITLE, NON-INFRINGEMENT AND FITNESS FOR A PARTICULAR
  PURPOSE. IN NO EVENT SHALL MICROCHIP OR ITS LICENSORS BE LIABLE OR
  OBLIGATED UNDER CONTRACT, NEGLIGENCE, STRICT LIABILITY, CONTRIBUTION,
  BREACH OF WARRANTY, OR OTHER LEGAL EQUITABLE THEORY ANY DIRECT OR INDIRECT
  DAMAGES OR EXPENSES INCLUDING BUT NOT LIMITED TO ANY INCIDENTAL, SPECIAL,
  INDIRECT, PUNITIVE OR CONSEQUENTIAL DAMAGES, LOST PROFITS OR LOST DATA,
  COST OF PROCUREMENT OF SUBSTITUTE GOODS, TECHNOLOGY, SERVICES, OR ANY
  CLAIMS BY THIRD PARTIES (INCLUDING BUT NOT LIMITED TO ANY DEFENSE THEREOF),
  OR OTHER SIMILAR COSTS.
 *****************************************************************************/
// DOM-IGNORE-END

#ifndef IMAGE_RESOURCES_EPD_2_0_INCH_DEMO_H_FILE
#define IMAGE_RESOURCES_EPD_2_0_INCH_DEMO_H_FILE
/*****************************************************************************
 * SECTION:  Includes
 *****************************************************************************/
#include <gfx/gfx.h>
#include <stdint.h>

/*****************************************************************************
 * SECTION:  Graphics Library Format Check
 *****************************************************************************/
#ifndef GFX_RESOURCE_FORMAT_VERSION
    #if(GRAPHICS_LIBRARY_VERSION != 0x0400)
    #warning "It is suggested to use Graphics Library version 4.00 or later with this version of GRC."
    #endif
#elif(GFX_RESOURCE_FORMAT_VERSION != 0x0100)
#warning "It is suggested to use Graphics Library with the resource format version 1.00 with this version of GRC."
#endif

/*****************************************************************************
 * SECTION:  Graphics Bitmap Padding Check
 *****************************************************************************/
#ifdef GFX_CONFIG_IMAGE_PADDING_DISABLE
#error These bitmap resources have been converted with padding of the horizontal lines, but GFX_CONFIG_IMAGE_PADDING_DISABLE is defined in system_config.h.
#endif



/*****************************************************************************
 * This is an error check for the color depth
 *****************************************************************************/
#if (GFX_CONFIG_COLOR_DEPTH > 16)
#error "Color Depth needs to be 16 to correctly use these resources"
#endif



/*****************************************************************************
 * SECTION:  BITMAPS
 *****************************************************************************/

/*********************************
 * Bitmap Structure
 * Label: GLA_barchart_BG_2_inch
 * Description:  200x96 pixels, 1-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR GLA_barchart_BG_2_inch;
#define GLA_barchart_BG_2_inch_WIDTH     (200)
#define GLA_barchart_BG_2_inch_HEIGHT    (96)
#define GLA_barchart_BG_2_inch_SIZE      (2410)
/*********************************
 * Bitmap Structure
 * Label: GLA_front_menu_BG_2_inch
 * Description:  200x96 pixels, 1-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR GLA_front_menu_BG_2_inch;
#define GLA_front_menu_BG_2_inch_WIDTH     (200)
#define GLA_front_menu_BG_2_inch_HEIGHT    (96)
#define GLA_front_menu_BG_2_inch_SIZE      (2410)
/*********************************
 * Bitmap Structure
 * Label: GLA_ECG_BG_2_inch
 * Description:  200x96 pixels, 1-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR GLA_ECG_BG_2_inch;
#define GLA_ECG_BG_2_inch_WIDTH     (200)
#define GLA_ECG_BG_2_inch_HEIGHT    (96)
#define GLA_ECG_BG_2_inch_SIZE      (2410)
/*********************************
 * Bitmap Structure
 * Label: GLA_HVAC_BG_2_inch
 * Description:  200x96 pixels, 1-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR GLA_HVAC_BG_2_inch;
#define GLA_HVAC_BG_2_inch_WIDTH     (200)
#define GLA_HVAC_BG_2_inch_HEIGHT    (96)
#define GLA_HVAC_BG_2_inch_SIZE      (2410)
/*********************************
 * Bitmap Structure
 * Label: ECG_2_inch
 * Description:  190x61 pixels, 1-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR ECG_2_inch;
#define ECG_2_inch_WIDTH     (190)
#define ECG_2_inch_HEIGHT    (61)
#define ECG_2_inch_SIZE      (1474)
/*********************************
 * Bitmap Structure
 * Label: Fan1
 * Description:  53x53 pixels, 1-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR Fan1;
#define Fan1_WIDTH     (53)
#define Fan1_HEIGHT    (53)
#define Fan1_SIZE      (381)
/*********************************
 * Bitmap Structure
 * Label: Fan2
 * Description:  53x53 pixels, 1-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR Fan2;
#define Fan2_WIDTH     (53)
#define Fan2_HEIGHT    (53)
#define Fan2_SIZE      (381)
/*********************************
 * Bitmap Structure
 * Label: Fan3
 * Description:  53x53 pixels, 1-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR Fan3;
#define Fan3_WIDTH     (53)
#define Fan3_HEIGHT    (53)
#define Fan3_SIZE      (381)
/*********************************
 * Bitmap Structure
 * Label: heart0
 * Description:  14x13 pixels, 1-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR heart0;
#define heart0_WIDTH     (14)
#define heart0_HEIGHT    (13)
#define heart0_SIZE      (36)
/*********************************
 * Bitmap Structure
 * Label: heart1
 * Description:  14x13 pixels, 1-bits per pixel
 ***********************************/
extern const GFX_RESOURCE_HDR heart1;
#define heart1_WIDTH     (14)
#define heart1_HEIGHT    (13)
#define heart1_SIZE      (36)
#endif

